services:
        python:
                build: .
                restart: always
                networks: ["imarg"]
                volumes:
                        - type: bind
                          source: .
                          target: /root
                        - type: bind
                          source: /tmp
                          target: /tmp
                        - type: bind
                          source: /mnt/ceph/storage/corpora/corpora-webis/corpus-touche-image-search-22/latest/
                          target: /data
                depends_on:
                        - elastic
                working_dir: /root

        elastic:
                image: "docker.elastic.co/elasticsearch/elasticsearch:7.15.2"
                restart: always
                networks: ["imarg"]
                ports:
                        - "9200:9200"
                        - "9300:9300"
                volumes:
                        - type: bind
                          source: ./elastic
                          target: /usr/share/elasticsearch/data
                environment:
                        - discovery.type=single-node
                healthcheck:
                        test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health"]
                cpus: 0.5
                mem_limit: 12g
networks:
        imarg:
